# Generated by Django 3.2.7 on 2021-11-30 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(default='None', max_length=50, verbose_name='Title')),
                ('company_name', models.TextField(default='None', max_length=50, verbose_name='Company Name')),
                ('description', models.TextField(default='None', max_length=150, verbose_name='Description')),
                ('eligibility', models.TextField(default='None', max_length=50, verbose_name='Eligibility')),
                ('link_to_apply', models.TextField(default='None', max_length=50, verbose_name='Link')),
                ('is_hackathon', models.BooleanField(default=False)),
                ('is_job', models.BooleanField(default=False)),
                ('is_internship', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
