# Generated by Django 3.2.7 on 2021-12-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='link_to_apply',
            field=models.TextField(default='None', max_length=200, verbose_name='Link'),
        ),
    ]
