# Generated by Django 3.2.7 on 2021-12-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_link_to_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='link_to_apply',
            field=models.TextField(default='None', max_length=1000, verbose_name='Link'),
        ),
    ]
