# Generated by Django 3.2.7 on 2021-12-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
