# Generated by Django 3.2.7 on 2021-11-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_appliedto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='image',
            field=models.ImageField(default='defaultprofilepic.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='defaultprofilepic.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='AppliedTo',
        ),
    ]
