# Generated by Django 3.2.7 on 2021-12-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211130_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emailid',
            field=models.EmailField(max_length=150, verbose_name='Email ID: '),
        ),
    ]
