# Generated by Django 3.2.7 on 2021-12-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningmaterial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='name',
            new_name='concept',
        ),
    ]
